url: https://mxcl.github.io/PromiseKit/
permalink: /news/:year/:month/:title/
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
