import_from_git(
  url: "git@bitbucket.org:24imedia/swift-sottfastlane.git", # The URL of the repository to import the Fastfile from.
  branch: "master", # The branch to checkout on the repository. Defaults to `HEAD`.
  path: "Fastfile_Version_Bump" # The path of the Fastfile in the repository. Defaults to `fastlane/Fastfile`.
  # version: "~> 1.0.0" # The version to checkout on the repository. Optimistic match operator can be used to select the latest version within constraints.
)
before_all do |lane, options|
  bundle_install
  sh('rm -rf ../output')
  sh('rm -rf ../derivedData')

end

lane :deploy do |params|
  bump_type = params[:bump_type]
  release_type = params[:release_type]
  xcversion(version:'10.1')
  version = pod_increase_version_number(podspec: 'PromiseKit.podspec', bump_type: bump_type, release_type: release_type)
  puts version
  push_to_git_remote(force: false, tags: true)
  sh("git fetch --tags")
  pod_push(path: "PromiseKit.podspec", repo: "SmartOTTIOSPods", swift_version: 4.2, allow_warnings: true, verbose: true, sources:["https://github.com/CocoaPods/Specs.git","https://bitbucket.org/24imedia/smart-ott-ios-pods.git"])
  sh("pod repo update")
end
